name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # ref: https://github.com/marketplace/actions/automated-build-android-app-with-github-action
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: gradle

    - name: Cache Gradle wrapper
      uses: actions/cache@v3
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Android build cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.android/build-cache
          ~/.gradle/caches
        key: ${{ runner.os }}-android-build-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-android-build-cache-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Print generated version
      run: ./gradlew --quiet androidGitVersion

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build apk debug project (APK)
      run: ./gradlew packageDebugAndroidTest